### ISSUE TITLE
Please use SQLAlchemy instead of PyMySQL

### ISSUE THREAD

**Issue by carolvv** [KEN-LJQ/ZhihuSpider#10]
SQLAlchemy is more flexible and do not need to execute seperate .SQL file.

**Comment by KEN-LJQ** [comment]
There is only a few place need to persist data, I think PyMySQL is good enough to do this job. But welcome to pull your request with SQLAlchemy

**Comment by carolvv** [comment]
hi，运行startup以后显示:

F:\spider>startup.py
Traceback (most recent call last):
  File "F:\spider\startup.py", line 1, in <module>
    from Core.SpiderCore import SpiderCore
  File "F:\spider\Core\SpiderCore.py", line 3, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'

但是我已经安装了redis了0 0

谢谢~~

**Comment by KEN-LJQ** [comment]
确定你已经安装了redis-py这个库了吗？

**Comment by carolvv** [comment]
F:\spider>pip3 install -r requirements.txt
Requirement already satisfied: beautifulsoup4==4.5.3 in c:\users\cyw\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: bs4==0.0.1 in c:\users\cyw\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: PyMySQL==0.7.10 in c:\users\cyw\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: redis==2.10.5 in c:\users\cyw\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: requests==2.13.0 in c:\users\cyw\appdata\local\programs\python\python35\lib\site-packages (from -r requirements.txt (line 5))

这个安装命令显示已经安装成功了吧？

**Comment by KEN-LJQ** [comment]
你好，从上面看是安装成功了。请问你有没有曾经在其他Python项目中成功import并使用redis这个库呢？或者成功import并使用过其他的第三方库，如Pymysql，requests等等？

**Comment by carolvv** [comment]
没有诶，这也是我第一次用python><

**Comment by KEN-LJQ** [comment]
要不加我QQ1120799726一起来研究一下

**Comment by carolvv** [comment]
哇0 0好呀，感谢！！
