### ISSUE TITLE
能不能获取用户的全部关注者和全部粉丝了？

### ISSUE THREAD

**Issue by huluobotouer** [KEN-LJQ/ZhihuSpider#2]

**Comment by KEN-LJQ** [comment]
你的意思是获取某一个用户的全部关注者和全部粉丝列表吗

**Comment by huluobotouer** [comment]
是获取某一个用户的全部关注者和全部粉丝列表吧，我的需求是获取某一位用户的全部关注者的ID和全部粉丝的ID

**Comment by KEN-LJQ** [comment]
可以的，我这个爬虫的原理就是从某一位用户开始，爬取他的关注者ID以及粉丝ID，然后再利用爬取到的这些用户ID继续循环的爬取。但是我的程序中对每个用户可以爬取的关注者和粉丝的数目作了限制（因为部分用户的关注者和粉丝有几十万），如果需要的话，只需要在我最新的一个提交中将 `core` 文件夹中的 `ScrapeCore.py` 文件中的 `FOLLOWING_PAGE_MAX` 和 `FOLLOWER_PAGE_MAX` 字段设置为负数再运行就可以了。另外要说明的是，现在我的爬虫只是保存了用户的信息，并没有保存用户之间的关注关系，不知道你有没有这个需求

**Comment by huluobotouer** [comment]
还确实有这方面的需求，我有很多个知乎用户ID，我想爬取他们之间的相关关系，关注关系只是其中的一种

**Comment by KEN-LJQ** [comment]
现在还没有这个功能，但很容易就可以在现有的基础上实现保存用户关注关系，至于要持久化的数据量就较大了。另外，用户间的相关关系除了关注关系还有什么？

**Comment by huluobotouer** [comment]
还有一些类似于答案的回复关系，点赞关系，答案评论关系之类的。

**Comment by huluobotouer** [comment]
还有啊，我发现是循环爬取哎。我想的是只要爬取一层就行了。不需要再起爬取他的粉丝的粉丝

**Comment by KEN-LJQ** [comment]
恐怕是不能满足你的需求了，修改的话估计改动也是比较大。我的设计就是为了让爬虫有再生能力，可以从初始提供的几个用户ID，爬取到几十万的不同用户的信息
