### ISSUE TITLE
Spider使用询问

### ISSUE THREAD

**Issue by LinuxBars** [KEN-LJQ/ZhihuSpider#4]
配置文件修改如下选项后：
# 爬虫起始token
startToken ='fu-wen-hui-48'
# 数据库配置
dbHost = localhost
dbUsername = root
dbPassword = root
dbDatabase = zhihu_spider
dbCharset = utf8
isEmailNotificationEnable = 0

运行爬虫 python startup.py 程序长期没有任何输出 不知道是哪里没有配置好：）
![screenshot from 2017-03-15 17-36-27](https://cloud.githubusercontent.com/assets/22124843/23942079/155048fa-09a6-11e7-8571-dd875e720170.png)

**Comment by KEN-LJQ** [comment]
是这样的，程序应该已经是正常运行了。只不过爬虫默认是把输出信息都放到日志文件里面，如果想在控制台看到输出的话，只需要修改`core/Logger.py`文件里面的`LOGGING_TYPE`字段为`consoleLogger`就可以了.
![1](https://cloud.githubusercontent.com/assets/16650282/23946415/46c8e43c-09b5-11e7-8b65-69f7bbe497b3.PNG)
